# This is mostly taken from source sdk 2013 community edition
# https://github.com/Nbc66/source-sdk-2013-ce/blob/master/.github/workflows/SP_windows.yml

name: windows build
on: workflow_dispatch

jobs:
  hl2chaos:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Choco
        run: choco install microsoft-build-tools-2013

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2013

      - name: Configure registry
        shell: powershell
        run: |
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "DefaultProjectExtension" /t REG_SZ  /d "vcxproj" /f /reg:32
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "PossibleProjectExtensions" /t REG_SZ /d "vcxproj;vcxitems;vcproj;mak" /f /reg:32

      - name: Create project files
        run: cd sp/src;./creategameprojects.bat

      - name: Build project
        run: cd sp/src;devenv games.sln /Build Release

      - name: Copy hl2 libraries
        shell: bash
        run: mkdir -p sourcemods/hl2chaos/bin; cp sp/game/mod_hl2/bin/{client,server}.dll sourcemods/hl2chaos/bin

      - name: Copy episodic libraries
        shell: bash
        run: mkdir -p sourcemods/ep1chaos/bin; cp sp/game/mod_episodic/bin/{client,server}.dll sourcemods/ep1chaos/bin; cp -R sourcemods/ep1chaos/bin sourcemods/ep2chaos

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hl2c
          path: sourcemods
